import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
//import Image from 'next/image';
//import background from 'public/background.jpg';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*<Image
          priority
          src={background}
          alt="background"
          layout="fill"
          objectFit='cover'
          className="-z-10"
        />*/}
        {children}
      </body>
    </html>
  )
}
